import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",passwd="5678",database="library_management_project")
mycursor=mydb.cursor()
def bookadd():
    bookIDp=input("ENTER THE BOOK'S ID:- ") 
    mycursor.execute("INSERT INTO BOOK (book_ID) VALUES (bookIDp)")
    mydb.commit()
    bktitlep=input("ENTER THE BOOK'S TITLE/NAME:- ")
    mycursor.execute("INSERT INTO BOOK (bktitle) VALUES (bktitlep)")
    mydb.commit()
    bkauthorp=input("ENTER THE BOOK'S AUTHOR NAME:- ")
    mycursor.execute("INSERT INTO BOOK (bkauthor) VALUES (bkauthorp)")
    mydb.commit()
    bkpublisherp=input("ENTER THE BOOK'S PUBLISHER NAME:- ")
    mycursor.execute("INSERT INTO BOOK (bkpubisher) VALUES (bkpublisherp)")
    mydb.commit()
    bkcopiesp=int(input("ENTER THE TOTAL NUMBER OF THE COPIES OF THIS BOOK:- "))
    mycursor.execute("INSERT INTO BOOK (bkcopies) VALUES (bkopiesp)")
    mydb.commit()
    bk_sourcep=input("ENTER THE BOOK'S SOURCE:- ")
    mycursor.execute("INSERT INTO BOOK (bk_source) VALUES (bk_sourcep)")
    mydb.commit()
    bk_costp=int(input("ENTER THE BOOK'S COST OF ONE UNIT:- "))
    mycursor.execute("INSERT INTO BOOK (bk_cost) VALUES (bk_costp)")
    mydb.commit()
    bk_remarksp=input("ENTER BOOK'S REMARKS:- ")
    mycursor.execute("INSERT INTO BOOK (bk_remarks) VALUES (bk_remarksp)")
    mydb.commit()
def bookupdate():
    bookIDp=input("ENTER THE BOOK'S ID:- ")
    mycursor.execute("UPDATE BOOK SET book_ID = bookIDp")
    mydb.commit()
    bktitlep=input("ENTER THE BOOK'S TITLE/NAME:- ")
    mycursor.execute("UPDATE USERS SET bktitles = bktitlesp")
    mydb.commit()
    bkauthorp=input("ENTER THE BOOK'S AUTHOR NAME:- ")
    mycursor.execute("UPDATE BOOK SET bkauthor = bkauthorp")
    mydb.commit()
    bkpublisherp=input("ENTER THE BOOK'S PUBLISHER NAME:- ")
    mycursor.execute("UPDATE BOOK SET bkpublisher = bkpublisherp")
    mydb.commit()
    bkcopiesp=int(input("ENTER THE TOTAL NUMBER OF THE COPIES OF THIS BOOK:- "))
    mycursor.execute("UPDATE BOOK SET bkcopies = bkcopiesp")
    mydb.commit()
    bk_sourcep=input("ENTER THE BOOK'S SOURCE:- ")
    mycursor.execute("UPDATE BOOK SET bk_source = bk_sourcep")
    mydb.commit()
    bk_costp=int(input("ENTER THE BOOK'S COST OF ONE UNIT:- "))
    mycursor.execute("UPDATE BOOK SET bk_cost = bk_costp")
    mydb.commit()
    bk_remarksp=input("ENTER BOOK'S REMARKS:- ")
    mycursor.execute("UPDATE BOOK SET bk_remarks = bk_remarksp")
    mydb.commit()
