import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",passwd="5678",database="library_management_project")
mycursor=mydb.cursor()
def returneestudentadd():
    Borrowers_IDp=int(input("ENTER YOUR BORROWERS_ID:- "))
    mycursor.execute("INSERT INTO BookReturnRecords (Borrowers_ID) VALUES (Borrowers_IDp)")
    mydb.commit()
    bookIDp=int(input("ENTER YOUR BOOK'S ID:- "))
    mycursor.execute("INSERT INTO BookReturnRecords (book_ID) VALUES (bookIDp)")
    mydb.commit()
    bktitlep=input("ENTER YOUR BOOK'S TITLE/NAME:- ")
    mycursor.execute("INSERT INTO BookReturnRecords (bktitle) VALUES (bktitlep)")
    mydb.commit()
    studIDp=input("ENTER YOUR STUDENT_ID:- ")
    mycursor.execute("INSERT INTO BookReturnRecords (stud_ID) VALUES (studIDp)")
    mydb.commit()
    stfnamep=input("ENTER YOUR FIRST NAME:- ")
    mycursor.execute("INSERT INTO BookReturnRecords (stfname) VALUES (stfnamep)")
    mydb.commit()
    releaseDatep=int(input("ENTER RELEASE DATE(MMDDYYYY):- "))
    mycursor.execute("INSERT INTO BookReturnRecords (releaseDate) VALUES (releaseDatep)")
    mydb.commit()
    duedatep=int(input("ENTER YOUR DUE DATE(MMDDYYYY):- "))
    mycursor.execute("INSERT INTO BookReturnRecords (duedate) VALUES (duedatep)")
    mydb.commit()
    bkdatereturnp=int(input("ENTER THE BOOK RETURN DATE(MMDDYYYY)"))
    mycursor.execute("INSERT INTO BookReturnRecords (bkdateturn) VALUES (bkdateturnp)")
    mydb.commit()
def returneestaffadd():
    Borrowers_IDp=int(input("ENTER YOUR BORROWERS_ID:- "))
    mycursor.execute("UPDATE BookReturnRecords SET Borrowers_ID = Borrowers_IDp")
    mydb.commit()
    bookIDp=int(input("ENTER YOUR BOOK'S ID:- "))
    mycursor.execute("UPDATE BookReturnRecords SET book_ID = book_IDp")
    mydb.commit()
    bktitlep=input("ENTER YOUR BOOK'S TITLE/NAME:- ")
    mycursor.execute("UPDATE BookReturnRecords SET bktitle= bktitlep")
    mydb.commit()
    staffIDp=input("ENTER YOUR STUDENT_ID:- ")
    mycursor.execute("UPDATE BookReturnRecords SET staff_ID = staffIDp")
    mydb.commit()
    stffnamep=input("ENTER YOUR FIRST NAME:- ")
    mycursor.execute("UPDATE BookReturnRecords SET stffname = stffnamep")
    mydb.commit()
    releaseDatep=int(input("ENTER RELEASE DATE(MMDDYYYY):- "))
    mycursor.execute("UPDATE BookReturnRecords SET releaseDate = releaseDatep")
    mydb.commit()
    duedatep=int(input("ENTER YOUR DUE DATE(MMDDYYYY):- "))
    mycursor.execute("UPDATE BookReturnRecords SET duedate = duedatep")
    mydb.commit()
    bkdatereturnp=int(input("ENTER THE BOOK RETURN DATE(MMDDYYYY)"))
    mycursor.execute("UPDATE  SET bkdateturn = bkdateturnp")
    mydb.commit()
