import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",passwd="5678",database="library_management_project")
mycursor=mydb.cursor()
def borrowerstudentadd():
    Borrowers_IDp=int(input("ENTER YOUR BORROWERS_ID:- "))
    mycursor.execute("INSERT INTO borrowers_records (Borrowers_ID) VALUES (Borrowers_IDp)")
    mydb.commit()
    bookIDp=int(input("ENTER YOUR BOOK'S ID:- "))
    mycursor.execute("INSERT INTO borrowers_records (book_ID) VALUES (bookIDp)")
    mydb.commit()
    bktitlep=input("ENTER YOUR BOOK'S TITLE/NAME:- ")
    mycursor.execute("INSERT INTO borrowers_records (bktitle) VALUES (bktitlep)")
    mydb.commit()
    studIDp=input("ENTER YOUR STUDENT_ID:- ")
    mycursor.execute("INSERT INTO borrowers_records (stud_ID) VALUES (studIDp)")
    mydb.commit()
    stfnamep=input("ENTER YOUR FIRST NAME:- ")
    mycursor.execute("INSERT INTO borrowers_records (stfname) VALUES (stfnamep)")
    mydb.commit()
    releaseDatep=int(input("ENTER RELEASE DATE(MMDDYYYY):- "))
    mycursor.execute("INSERT INTO borrowers_records (releaseDate) VALUES (releaseDatep)")
    mydb.commit()
    duedatep=int(input("ENTER YOUR DUE DATE(MMDDYYYY):- "))
    mycursor.execute("INSERT INTO borrowers_records (duedate) VALUES (duedatep)")
    mydb.commit()
def borrowerstaffadd():
    Borrowers_IDp=int(input("ENTER YOUR BORROWERS_ID:- "))
    mycursor.execute("UPDATE borrowers_records SET Borrowers_ID = Borrowers_IDp")
    mydb.commit()
    bookIDp=int(input("ENTER YOUR BOOK'S ID:- "))
    mycursor.execute("UPDATE borrowers_records SET book_ID = book_IDp")
    mydb.commit()
    bktitlep=input("ENTER YOUR BOOK'S TITLE/NAME:- ")
    mycursor.execute("UPDATE borrowers_records SET bktitle= bktitlep")
    mydb.commit()
    staffIDp=input("ENTER YOUR STUDENT_ID:- ")
    mycursor.execute("UPDATE borrowers_records SET staff_ID = staffIDp")
    mydb.commit()
    stffnamep=input("ENTER YOUR FIRST NAME:- ")
    mycursor.execute("UPDATE borrowers_records SET stffname = stffnamep")
    mydb.commit()
    releaseDatep=int(input("ENTER RELEASE DATE(MMDDYYYY):- "))
    mycursor.execute("UPDATE borrowers_records SET releaseDate = releaseDatep")
    mydb.commit()
    duedatep=int(input("ENTER YOUR DUE DATE(MMDDYYYY):- "))
    mycursor.execute("UPDATE borrowers_records SET duedate = duedatep")
    mydb.commit()
