import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",passwd="5678",database="library_management_project")
mycursor=mydb.cursor()
def useradd():
    studIDp=int(input("ENTER YOUR STUDENT_ID:- "))
    stfnamep=input("ENTER YOUR FIRST NAME:- ")
    stlnamep=input("ENTER YOUR LAST NAME:- ")
    stcoursep=input("ENTER YOUR COURSE:- ")
    styearp=int(input("ENTER YOUR ADMISSION YEAR:- "))
    stcontactp=int(input("ENTER YOUR CONTACT NUMBER:- "))
    stagep=int(input("ENTER YOUR AGE:- "))
    stbirthdatep=int(input("ENTER YOUR DATE OF BIRTH(MMDDYYYY):- "))
    stgenderp=input("ENTER YOUR GENDER:- ")
    sql = "INSERT INTO students (stud_ID, stfname, stlname, stcourse, styear, stcontact, stage, stbirthdate, stgender) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)"
    val = (studIDp, stfnamep, stlnamep, stcoursep, styearp, stcontactp, stagep, stbirthdatep, stgenderp)
    mycursor.execute(sql, val)
    mydb.commit()
    print(mycursor.rowcount, "was inserted.")
def userupdate():
    studIDp=int(input("ENTER YOUR STUDENT_ID:- "))
    stfnamep=input("ENTER YOUR FIRST NAME:- ")
    stlnamep=input("ENTER YOUR LAST NAME:- ")
    stcoursep=input("ENTER YOUR COURSE:- ")
    styearp=int(input("ENTER YOUR ADMISSION YEAR:- "))
    stcontactp=int(input("ENTER YOUR CONTACT NUMBER:- "))
    stagep=int(input("ENTER YOUR AGE:- "))
    stbirthdatep=int(input("ENTER YOUR DATE OF BIRTH(MMDDYYYY):- "))
    stgenderp=input("ENTER YOUR GENDER:- ")
    sql = "UPDATE STUDENTS SET stud_ID = %s, stfname = %s, stlname = %s, stcourse = %s, styear = %s, stcontact = %s, stage = %s, stbirthdate = %s, stgender = %s WHERE stud_ID = studID"
    val = (studIDp, stfnamep, stlnamep, stcoursep, styearp, stcontactp, stagep, stbirthdatep, stgenderp)
    mycursor.execute(sql,val)
    mydb.commit()
    print(mycursor.rowcount, "records updated")
