import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",passwd="5678",database="library_management_project")
mycursor=mydb.cursor()
def useradd():
    staffIDp=int(input("ENTER YOUR STAFF_ID:- "))
    stffnamep=input("ENTER YOUR FIRST NAME:- ")
    stflnamep=input("ENTER YOUR LAST NAME")
    stfcontactnumberp=int(input("ENTER YOUR CONTACT NUMBER:- "))
    stfemailp=input("ENTER YOUR EMAIL_ID:- ")
    stfaddressp=input("ENTER YOUR ADDRESS:- ")
    stfpasswordp=input("ENTER YOUR PASSWORD:- ")
    stftypep=input("ENTER YOUR STAFF TYPE:- ")
    sql = "INSERT INTO USERS (staff_ID, stffname, stflname, stfcontactnumber, stfemail, stfaddress, stfpassword, stftype) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)"
    val = (staffIDp, stffnamep, stflnamep, stfcontactnumberp, stfemailp, stfaddressp, stfpasswordp, stftypep)
    mycursor.execute(sql, val)
    mydb.commit()
    print(mycursor.rowcount, "was inserted.")
def userupdate():
    staffIDp=int(input("ENTER YOUR STAFF_ID:- "))
    stffnamep=input("ENTER YOUR FIRST NAME:- ")
    stflnamep=input("ENTER YOUR LAST NAME:- ")
    stfcontactnumberp=int(input("ENTER YOUR CONTACT NUMBER:- "))
    stfemailp=input("ENTER YOUR EMAIL_ID:- ")
    stfaddressp=input("ENTER YOUR ADDRESS:- ")
    stfpasswordp=input("ENTER YOUR PASSWORD:- ")
    stftypep=input("ENTER YOUR STAFF TYPE:- ")
    sql = "UPDATE USERS SET staff_ID = %s, stffname = %s, stflname = %s, stfcontactnumber = %s, stfemail = %s, stfaddress = %s, stfpassword = %s, stftype = %s WHERE staff_ID = staffID"
    val = (staffIDp, stffnamep, stflnamep, stfcontactnumberp, stfemailp, stfaddressp, stfpasswordp, stftypep)
    mycursor.execute(sql,val)
    mydb.commit()
    print(mycursor.rowcount, "records updated")
