import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",passwd="5678",database="library_management_project")
mycursor=mydb.cursor()
def useradd():
    staffIDp=int(input("ENTER YOUR STAFF_ID:- "))
    mycursor.execute("INSERT INTO USERS (staff_ID) VALUES (staffIDp)")
    mydb.commit()
    stffnamep=input("ENTER YOUR FIRST NAME:- ")
    mycursor.execute("INSERT INTO USERS (stffname) VALUES (stffnamep)")
    mydb.commit()
    stflnamep=input("ENTER YOUR LAST NAME")
    mycursor.execute("INSERT INTO USERS (stflname) VALUES (stflnamep)")
    mydb.commit()
    stfcontactnumberp=int(input("ENTER YOUR CONTACT NUMBER:- "))
    mycursor.execute("INSERT INTO USERS (stfcontactnumber) VALUES (stfcontactnumberp)")
    mydb.commit()
    stfemailp=input("ENTER YOUR EMAIL_ID:- ")
    mycursor.execute("INSERT INTO USERS (stfemail) VALUES (stfemailp)")
    mydb.commit()
    stfaddressp=input("ENTER YOUR ADDRESS:- ")
    mycursor.execute("INSERT INTO USERS (stfaddress) VALUES (stfaddressp)")
    mydb.commit()
    stfpasswordp=input("ENTER YOUR PASSWORD:- ")
    mycursor.execute("INSERT INTO USERS (stfpassword) VALUES (stfpasswordp)")
    mydb.commit()
    stftypep=input("ENTER YOUR STAFF TYPE:- ")
    mycursor.execute("INSERT INTO USERS (stftype) VALUES (stftypep)")
    mydb.commit()
def userupdate():
    staffIDp=int(input("ENTER YOUR STAFF_ID:- "))
    mycursor.execute("UPDATE USERS SET staff_ID = staffIDp")
    mydb.commit()
    stffnamep=input("ENTER YOUR FIRST NAME:- ")
    mycursor.execute("UPDATE USERS SET stffname = stffnamep")
    mydb.commit()
    stflnamep=input("ENTER YOUR LAST NAME"
    mycursor.execute("UPDATE USERS SET stflname = stflnamep")
    mydb.commit()
    stfcontactnumberp=int(input("ENTER YOUR CONTACT NUMBER:- "))
    mycursor.execute("UPDATE USERS SET stfcontactnumber = stfcontactnumberp")
    mydb.commit()
    stfemailp=input("ENTER YOUR EMAIL_ID:- ")
    mycursor.execute("UPDATE USERS SET stfemail = stfemailp")
    mydb.commit()
    stfaddressp=input("ENTER YOUR ADDRESS:- ")
    mycursor.execute("UPDATE USERS SET stfaddress = stfaddressp")
    mydb.commit()
    stfpasswordp=input("ENTER YOUR PASSWORD:- ")
    mycursor.execute("UPDATE USERS SET stfpassword = stfpasswprdp")
    mydb.commit()
    stftypep=input("ENTER YOUR STAFF TYPE:- ")
    mycursor.execute("UPDATE USERS SET stftype = stftypep")
    mydb.commit()
